### ISSUE TITLE
Support for Google Cloud Storage URLs

### ISSUE THREAD

**Issue by j08lue** [developmentseed/titiler#1021]
Once

- #1013 

is done, we should consider porting the support for GCS proposed in

- https://github.com/developmentseed/titiler-xarray/pull/51

Into the reader here. Looks like the changes in that PR were minimal and were just missing some tests.

**Comment by vincentsarago** [comment]
done in https://github.com/developmentseed/titiler/pull/1013/commits/97eb64885c140806a8ce00619ef520458f86e686

**Comment by j08lue** [comment]
![image](https://github.com/user-attachments/assets/c72815a2-d9fd-4834-bb6f-4dd5d064dbbe)
