### ISSUE TITLE
Issue applying a colormap to COG with nodata value

### ISSUE THREAD

**Issue by akatkov7** [developmentseed/titiler#1023]
#### Problem description

When I attempt to tile my COG with a nodata value outside of the range of 0 to 255, I get an exception when applying the colormap that the nodata value is not found in the colormap.

Originally, my COG was using the Type=Byte and just using 0 to 255 (with areas with nodata being set to 0) and that worked great.

Then, I needed to start distinguishing between which areas had nodata and which areas had a value of 0 so I changed the type of the tiff to Int16, changed the nodata areas to be -32768. and left the areas with data to be 0 to 255. This works great in MosaicJSON as it lets me fill in the nodata areas in one COG with the data in another COG. But when I try to just tile a single COG file that has this new setup, it gets this exception instead.

To me, this seems like a bug since it works as desired in the MosaicJSON tiles, but maybe this exception is expected for the COG tiles.

Let me know if you need any additional info. Thanks for the library!

```
  File "titiler/core/factory.py", line 622, in tile
    content, media_type = render_image(
                          ^^^^^^^^^^^^^
  File "titiler/core/utils.py", line 62, in render_image
    data, alpha_from_cmap = apply_cmap(data, colormap)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rio_tiler/colormap.py", line 115, in apply_cmap
    data = lookup_table[data[0], :]
           ~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: index -32768 is out of bounds for axis 0 with size 256
```

Sample URL that I am requesting: `http://localhost:45335/tiles/WebMercatorQuad/2/0/1@1x.png?url=cog.tiff&colormap_name=plasma`

#### Expected Output

This may be the expected behavior, but I'm not sure how to fix it if it is.

In my use case, my desire is that my nodata value would be transparent in my output.

#### Environment Information

Mac M1, 14.6.1 (23G93)
Python 3.11.10
titiler 0.18.10

#### More info

gdalinfo for the COG:
```
Driver: GTiff/GeoTIFF
Files: ***
Size is 3584, 2304
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            MEMBER["World Geodetic System 1984 (G2296)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Popular Visualisation Pseudo-Mercator",
        METHOD["Popular Visualisation Pseudo Mercator",
            ID["EPSG",1024]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Web mapping and visualisation."],
        AREA["World between 85.06°S and 85.06°N."],
        BBOX[-85.06,-180,85.06,180]],
    ID["EPSG",3857]]
Data axis to CRS axis mapping: 1,2
Origin = (-15028131.257091931998730,7514065.628545965999365)
Pixel Size = (2445.984905125640125,-2445.984905125640125)
Metadata:
  OVR_RESAMPLING_ALG=NEAREST
  TILING_SCHEME_NAME=WebMercatorQuad
  TILING_SCHEME_ZOOM_LEVEL=6
  AREA_OR_POINT=Area
Image Structure Metadata:
  LAYOUT=COG
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-15028131.257, 7514065.629) (135d 0' 0.00"W, 55d46'35.66"N)
Lower Left  (-15028131.257, 1878516.407) (135d 0' 0.00"W, 16d38'10.29"N)
Upper Right (-6261721.357, 7514065.629) ( 56d15' 0.00"W, 55d46'35.66"N)
Lower Right (-6261721.357, 1878516.407) ( 56d15' 0.00"W, 16d38'10.29"N)
Center      (-10644926.307, 4696291.018) ( 95d37'30.00"W, 38d49'21.33"N)
Band 1 Block=256x256 Type=Int16, ColorInterp=Gray
  NoData Value=-32768
  Overviews: 1792x1152, 896x576, 448x288, 224x144
```

**Comment by vincentsarago** [comment]
Default colormaps can only work with 8bytes dataset going from 0 to 255 

Maybe we could move https://github.com/cogeotiff/rio-tiler/blob/dd5ce03f8f463ec93f3a8787d7155d318397cd7c/rio_tiler/colormap.py#L127-L130 couple line up to make sure we ignore values outside those bounds.

It worked for mosaic because when we construct mosaic tiles we exclude nodata value from the data but it's not possible for non-mosaic tiles.

> Then, I needed to start distinguishing between which areas had nodata and which areas had a value of 0 so I changed the type of the tiff to Int16, changed the nodata areas to be -32768. 

This seems a bit weird, changing the datatype just to have a nodata value. I would use internal mask or alpha band for this and keep the datatype as byte 🤷 

as a quick (and dirty) fix you can apply `rescale=0,255` to your request and it will cast the values!

**Comment by akatkov7** [comment]
Thanks for the quick response!

> This seems a bit weird, changing the datatype just to have a nodata value. I would use internal mask or alpha band for this and keep the datatype as byte 🤷

Could you explain these options a bit more? I'm open to taking a different approach than my Int16 change if it accomplishes the same goal.

For the alpha band option, are you suggesting adding another band to the tiff which would identify the nodata areas instead? If so, would I then need to use expression to do multiply the bands together (assuming alpha band = 0 where nodata) or something else?

**Comment by vincentsarago** [comment]
UINT16 data takes more bytes than UINT8 datatype, meaning that you'll end up having a heavier file but also means that you'll transfer more bytes when reading the data. 

For the alpha band, yes it's an additional band to add to your file (so adds a bit of weight but is super light once compressed

**Comment by akatkov7** [comment]
I switched to writing an internal mask using rasterio with GDAL_TIFF_INTERNAL_MASK=true and write_mask and it seems to work for both COG tiles and MosaicJSON tiles so thank you for the suggestion!

As for this issue, I'll leave it up to you if my original usage was a valid case to handle whether by clamping or perhaps a more descriptive error message.

**Comment by vincentsarago** [comment]
thanks for the update @akatkov7 

I'll close this because it's really an edge case. But I'll see if we can patch this in rio-tiler
