### ISSUE TITLE
align with NumpyTile format

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#103]
In 
https://github.com/developmentseed/titiler/blob/e8d1304fd570bc01fe80c2573e778be1d8e5dbfd/titiler/utils.py#L68-L72

we save the data as a tuple .... but we should save it directly as a numpy array, adding the mask as the last band! 

ref: https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html#module-numpy.lib.format

**Comment by kylebarron** [comment]
Is there always a mask?

**Comment by vincentsarago** [comment]
> Is there always a mask? Is there a case where the user wouldn't want the mask as the last band? Would it be worthwhile to have an image format param that turns off including the mask as the last band?

well, I'll prefer to add mask by default every time (because mask is always returned by rio-tiler. But if we go ahead with the change directly in `rio_tiler.utils.render`, the `mask` value is optional here so I guess it will be up to the API side to add the mask or not (but by default titiler code will add the mask)

**Comment by kylebarron** [comment]
I think it's important for the API to be explicit, because the client needs to be able to know whether the last band is a mask or not.

**Comment by vincentsarago** [comment]
what `API` are you refering too @kylebarron ?

**Comment by kylebarron** [comment]
In titiler, if the user asks for an NPY response, should they be able to provide a param that turns off including the mask?

**Comment by vincentsarago** [comment]
well IMO titiler default code should always add mask in the data, it's up to user to built their own custom solution if they don't want the mask to be included. 

Not that I don't like the idea of not adding the mask, I just want to avoid too many options that won't be used by most users!

**Comment by kylebarron** [comment]
Is there not already an option to turn off the mask (generally)? I thought there had been in `cogeo-mosaic-tiler`, though maybe that was something I added.

**Comment by vincentsarago** [comment]
> Is there not already an option to turn off the mask (generally)? I thought there had been in cogeo-mosaic-tiler, though maybe that was something I added.

I don't think so.
