### ISSUE TITLE
Add stack config option for dynamodb permissions

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/titiler#114]
There's already a config option for _buckets_; there should also be an option to turn on permissions for reading from dynamodb tables.

E.g. I needed:
```py
    perms.append(
        iam.PolicyStatement(
            actions=["dynamodb:GetItem"],
            resources=[f"arn:aws:dynamodb:{deployment_region}:{aws_id}:table/*"],
        )
    )
```
to give read access to all tables in the defined region. It might make sense to also optionally have a list of table names instead of "all tables in region"

**Comment by vincentsarago** [comment]
@kylebarron there is a commented block in the stack.py already for this https://github.com/developmentseed/titiler/blob/fa711c0591dc8537caa8ebb68d303cb67f89b0f0/stack/app.py#L187-L199

Given that using dynamoDB table is only for mosaic and for expert user like yourself I didn't feel like adding some code by default. IMO everything in `/stack` is mostly to be used `as example`, users should understand they must edit it to serve their custom needs.

For the docs:
> The TiTiler repository includes an example that uses AWS CDK to deploy TiTiler on AWS' Elastic Container Service (ECS).

I'll make sure to add a note for the user to understand they should edit the stack.py to fit their needs.
