### ISSUE TITLE
Expensive NAT charges when deployed to ECS

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/titiler#119]
I deployed titiler to ECS, never touched it (besides making sure it worked), and then four days later checked and had $150 in NAT charges, with **3TB** of "Data Processed by NAT Gateways" at $0.045/GB. The egress bandwidth is only 1.694 GB, however, so nearly all of this data was inbound to the tiler.

The logs all look like this:
![image](https://user-images.githubusercontent.com/15164633/94481284-b77ad480-0194-11eb-84ee-8dd349d1de71.png)

There are such logs nearly every second:
![image](https://user-images.githubusercontent.com/15164633/94481368-d1b4b280-0194-11eb-86ac-6d693e270d41.png)

It looks similar to this issue: https://github.com/tiangolo/fastapi/issues/253. There are several configuration settings in the fastapi [docker options](https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi).

**Comment by MiroslavHrcan** [comment]
So actually what is the solution here? To avoid this? Setting up max_workers or just not to use Fargate? Or something else?

**Comment by vincentsarago** [comment]
@MiroslavHrcan https://github.com/developmentseed/titiler/blob/master/deployment/aws/cdk/config.py#L48-L68

yes setting max_workers env should fix the issue!

**Comment by MiroslavHrcan** [comment]
Is there maybe a way how to completely disable this GET request (is this some kind of health check?) to be sent?

Thx for the previous answer.
