### ISSUE TITLE
TilerFactory::tile breakup?

### ISSUE THREAD

**Issue by fredliporace** [developmentseed/titiler#141]
Salut!

I'm working on a custom tiler based on titiler that use tensorflow inference to generate a classification based on a STAC item's assets. Will include a reference to the repo as soon as it is stable.

The custom tiler uses TilerFactory and needs to re-implement the /tiles/* endpoints to return the classification result instead of assets' raster data. So I'm defining a new tile() function for my custom tiler.

Problem is since I also need the /tilejson endpoint and these are registered within tile() I also need to define the /tilejson/* routes in my tile() function, even though the implementation at the base class could be used as they are defined right now. I'm currently simply copying the tile()::tilejson() to my custom tiler.

One way I see to deal with this is to break the tile() function in TileFactory in two. Does that make sense? If yes I can work on a PR.

**Comment by vincentsarago** [comment]
hey @fredliporace, this has been annoying me too, I guess my though was, if you don't add the `tile()` function you don't need the tilejson and wmts endpoints.

That's say I'll be totally open to review a PR that breaks the `tile()` function into 3 `tile(), wmts(), tilejson()` 👍

**Comment by fredliporace** [comment]
@vincentsarago great! Will work on that then.

**Comment by vincentsarago** [comment]
@fredliporace I just push some big changes in Master, make sure to sync your branch. If you haven't started working on that yet, I could maybe do it tomorrow!

**Comment by fredliporace** [comment]
@vincentsarago working on it right now, alse detected the starlette issue you mentioned. I'll sync and try to submit the PR today.
