### ISSUE TITLE
Wrong CDK module for Lambda Proxy

### ISSUE THREAD

**Issue by michaelconnor00** [developmentseed/titiler#152]
I was launching the lambda CDK stack, and got an exception:
```
Traceback (most recent call last):
  File "stack/app.py", line 264, in <module>
    env=settings.additional_env,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "stack/app.py", line 88, in __init__
    default_integration=apigw.LambdaProxyIntegration(handler=lambda_function),
AttributeError: module 'aws_cdk.aws_apigatewayv2' has no attribute 'LambdaProxyIntegration'
```
Looking at https://github.com/developmentseed/titiler/blob/master/stack/app.py#L88, the class `LambdaProxyIntegration` is in the ` aws_cdk.aws_apigatewayv2_integrations` module, not the ` aws_cdk.aws_apigatewayv2` module.

**Comment by vincentsarago** [comment]
Yes, this is due to a recent change in CDK. I'm not sure I'll have time right now to make the change but if you want to make a PR I'll be happy to review! 

Note: we should maybe pin CDK to a specific version to avoid this in the future!

**Comment by kylebarron** [comment]
FYI I successfully deployed cdk to Lambda using 

```
> cdk --version
1.65.0 (build 1c2cba4)
```

**Comment by michaelconnor00** [comment]
I am using. 1.73.0. I will try downgrading. Thanks.
