### ISSUE TITLE
MosaicJSON notebook example not working

### ISSUE THREAD

**Issue by giswqs** [developmentseed/titiler#160]
It seems the [MosaicJSON notebook example](https://developmentseed.org/titiler/examples/Working_with_MosaicJSON/) no longer works. `s = soup.findAll('a')` does not return any content contain "tif". Is it because digitalglobe changed their webpage recently? 

![](https://i.imgur.com/iltF9NW.png)

**Comment by vincentsarago** [comment]
thanks for the report @giswqs
I've fixed this but I now have another issue with our `public` stack that will get fixed in the afternoon. Also again, feel free to use cogeo.xyz API but remember that it's a `use for DEMO only` endpoint 😉

**Comment by giswqs** [comment]
@vincentsarago Thanks for the quick fix. And yes, I understand that api.cogeo.xyz is a demo only endpoint. The [add_COG_layer()](https://geemap.org/geemap/#geemap.geemap.Map.add_COG_layer) in geemap allow users to use their own endpoint. I am also trying to set up an endpoint myself.

**Comment by giswqs** [comment]
BTW, I was able to fix the BeautifulSoup error, but I got another error (AccessDeniedException) during step 5.2 (Create Mosaic). [Here](https://gist.github.com/giswqs/1078742fc65ac05e67c4473dbe6be851) is the notebook I am using. Is it because the demo endpoint no longer allows anonymous users to create mosaic?  
![](https://i.imgur.com/bSVVvd0.png)

**Comment by vincentsarago** [comment]
yes that's what I'm fixing right now!

**Comment by vincentsarago** [comment]
stack and notebook have been updated 

closed by https://github.com/developmentseed/titiler/commit/e81c52e549234e362689c4f3f500b077c4d9f495

**Comment by giswqs** [comment]
I just tested the updated notebook and encountered an error. 

![](https://i.imgur.com/g8lkqEi.png)

**Comment by vincentsarago** [comment]
🤔 so it fails to get the bbox from the files... this work on my local machine, not sure what's going on for you!

**Comment by giswqs** [comment]
I created a fresh conda env to test it. The rasterio version is v1.1.8. 

```
conda create -n tiler python=3.8
pip install rasterio ipyleaflet requests tqdm bs4 requests
pip install rio-tiler cogeo-mosaic --pre
```

**Comment by vincentsarago** [comment]
the errors comes from the fact you can't retrieve the info from the files (not from the titiler API). 

On the block you shared can you print `responses`?

**Comment by giswqs** [comment]
Indeed, the `responses` variable is empty. [Here](https://nbviewer.jupyter.org/gist/giswqs/e36b96f410858c38cdd2ad06b7b434f3) is the notebook with outputs.

**Comment by vincentsarago** [comment]
oh I think this is because you are using binder, you need to set `CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` I guess.

**Comment by giswqs** [comment]
Setting `CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` did the trick! Thank you very much for your help!

![](https://i.imgur.com/oqU73oB.png)

**Comment by kylebarron** [comment]
I think the newest version of `rasterio` should fix this, but yeah this is necessary for now

**Comment by giswqs** [comment]
How to overwrite an existing mosaic layer? Where to put `overwrite=True`? Inside the json dict or params dict? I tried both, it seems not working.

![](https://i.imgur.com/6DIMTKP.png)

**Comment by vincentsarago** [comment]
ah that's the new feature on cogeo-mosaic and the API is not ready for this 🤦

I'm sorry that the full api for cogeo.xyz is not public (the only diff is the token auth). I'll try to fix this tonight @giswqs

**Comment by giswqs** [comment]
Good to know. Thanks a lot for your time.

**Comment by vincentsarago** [comment]
@giswqs sorry it took so long, but this is fixed in api.cogeo.xyz

**Comment by giswqs** [comment]
@vincentsarago Thanks for the fix. Where should I put `overwrite=True`? 

![](https://i.imgur.com/6DIMTKP.png)

**Comment by vincentsarago** [comment]
in the body
```
json={
    username:
    layername:
    files:
    overwrite=True
}
```
