### ISSUE TITLE
Better Binder hub integration for notebook demo

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#162]
Right now, when trying to launch binder hub to try the demo notebook, binder will install `titiler` module which is not really a dependencies. Most of the demo rely mainly on `requests` and `ipyleaflet` so there is no really need for a complex install.

**Comment by kylebarron** [comment]
https://mybinder.readthedocs.io/en/latest/using/config_files.html

**Comment by dchirst** [comment]
@vincentsarago was looking at this issue and think it might be closed? The [binder requirements](https://github.com/developmentseed/titiler/blob/main/.binder/requirements.txt) no longer has titiler in it.
