### ISSUE TITLE
Add `rasterio.env` block in each method to allow factory defined gdal config

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#168]
in https://github.com/developmentseed/titiler/pull/108 we introduced custom API route to wrap any gdal code within a specific environment. This worked well for python 3.7 but not for python 3.8. IMO adding a `with rasterio.env():` block on top of each call to gdal (rio-tiler) code will make this easier.

### How To
- add `gdal_config` in `titiler.endpoints.factories.BaseFactory` with default to `dict`
- add `with rasterio.env(**self.gdal_config):` on top of gdal blocks

**Comment by kylebarron** [comment]
> This worked well for python 3.7 but not for python 3.8

Why not? Is the change here in Python, or rasterio, or GDAL?

**Comment by vincentsarago** [comment]
I think there is a change in python, I think adding the `with rasterio.Env` is less of a hack anyway!
