### ISSUE TITLE
url in README.md

### ISSUE THREAD

**Issue by jsga** [developmentseed/titiler#17]
Hello,

the _README.md_ says:

`:endpoint:/v1/{z}/{x}/{y}[@{scale}x][.{ext}]`
```
(...)
- **url**: Cloud Optimized GeoTIFF URL. **REQUIRED**
```
I don't quite get where and how the **url** and the rest of the parameters are specified. Could you provide a specific example?

By the way, the tool seems awesome thanks :)

**Comment by vincentsarago** [comment]
thanks for the issue @jsga 
All parameters after `ext` must be passed as queryStrings e.g 

`:endpoint:/v1/{z}/{x}/{y}@{scale}x.{ext}?url=my.tif&rescale=1,2000` 

I'll update the documentation 🙏
