### ISSUE TITLE
Creating tiles from locally stored COGs

### ISSUE THREAD

**Issue by dzanaga** [developmentseed/titiler#180]
Hi :) 
I was trying to use `titiler` to visualize a mosaic in jupyter (or a leaflet) from local files and I have the following issue:

I have a set of COGs (in different EPSGs) covering Italy and I am trying to follow a bit this [example](https://developmentseed.org/titiler/examples/Working_with_MosaicJSON/) but doing everything locally:

After installing everything I start `titiler` with:
```
uvicorn titiler.main:app --reload --port 8501
```
And I get the API at `http://localhost:8501/docs`

Then in my notebook:
```
import glob

import requests
from ipyleaflet import Map, basemaps, TileLayer, basemap_to_tiles, GeoJSON


def mj_create(endpoint, files, url):
    
    r = requests.post(
            f"{endpoint}/mosaicjson",
            json={
                "files": files,
                "url": url,
            },
        ).json()
    
    return r

cogs_folder = '/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map'

files = glob.glob(cogs_folder + '*.tif')
files = files[:5]

endpoint = 'http://localhost:8501'

mj_url = "italy5"

r = mj_create(endpoint, files, mj_url)

r
```
which prints:
```
{'mosaicjson': '0.0.2',
 'version': '1.0.0',
 'minzoom': 7,
 'maxzoom': 13,
 'quadkey_zoom': 7,
 'bounds': [11.36110904209143,
  40.5048858361439,
  15.128266945123777,
  46.95370914193456],
 'center': [13.244687993607602, 43.729297489039226, 7],
 'tiles': {'1202302': ['/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TUL_map_cog_expert_v3_italy.tif',
   '/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TVM_map_cog_expert_v3_italy.tif',
   '/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TUK_map_cog_expert_v3_italy.tif'],
  '1202303': ['/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TVM_map_cog_expert_v3_italy.tif'],
  '1202320': ['/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TUL_map_cog_expert_v3_italy.tif',
   '/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TUK_map_cog_expert_v3_italy.tif'],
  '1202322': ['/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/32TQL_map_cog_expert_v3_italy.tif',
   '/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TTF_map_cog_expert_v3_italy.tif'],
  '1220100': ['/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/32TQL_map_cog_expert_v3_italy.tif',
   '/data/worldcover/runs/tenpercent/10percent_expert/v3/cogs/italy/map/33TTF_map_cog_expert_v3_italy.tif']}}
```
This is the same as generating it with `cogeo-mosaic`.

Finally I try to visualize them:
```
r = requests.get(
        f"{endpoint}/mosaicjson/tilejson.json",
        params={
            "url": mj_url
        }
    ).json()

bounds = r['bounds']
m = Map(
    center=((bounds[1] + bounds[3]) / 2,(bounds[0] + bounds[2]) / 2),
    zoom=10
)

tiles = TileLayer(
    url=r["tiles"][0],
    min_zoom=r["minzoom"],
    max_zoom=r["maxzoom"],
    opacity=1
)

m.add_layer(tiles)
m
```

But here I see only the base map and no rasters from titiler...

This is `r`:
```
{'tilejson': '2.2.0',
 'name': 'italy5',
 'version': '1.0.0',
 'scheme': 'xyz',
 'tiles': ['http://localhost:8501/mosaicjson/tiles/WebMercatorQuad/{z}/{x}/{y}@1x?url=italy5'],
 'minzoom': 7,
 'maxzoom': 13,
 'bounds': [11.36110904209143,
  40.5048858361439,
  15.128266945123777,
  46.95370914193456],
 'center': [13.244687993607602, 43.729297489039226, 7]}
```

If I remember correctly I generated these COGs with `rio-cogeo`.

I can't figure out what's wrong, I am not getting any error message or hints and wasn't able to figure it out from the code. Any idea? I can share a couple of my tifs if needed.

**Comment by vincentsarago** [comment]
It's interesting because the mosaic is created and can be read TiTiler. 

The tiles should be appearing between zoom 7 and 13, but I don't know why you don't see anything. Does uvicorn show any logs? if not it will means that leafleft is not doing any request 🤷‍♂️

**Comment by dzanaga** [comment]
it actually works in the end... I went for lunch and when I came back there were tiles. So it seems the problem was more that I was panning around and zooming too fast to give it time to tile the rasters perhaps... or I don't know. But now I can see them!
Thanks anyway :) I just thought there was maybe some issue with my get requests as the documentation example runs with another version of the app, so that was a bit confusing initially.

Btw the I had a colormap written to the tifs with rasterio. When I use `rio-viz` that's plotted as well. With `titiler` I see the tiles in gray scale, is there a way to display the tiles with colors?

**Comment by vincentsarago** [comment]
> Btw the I had a colormap written to the tifs with rasterio. When I use rio-viz that's plotted as well. With titiler I see the tiles in gray scale, is there a way to display the tiles with colors?

yes this is expected because it's a mosaic, it's hard to know if we should use the internal mosaic (e.g what if some COG don't have colormap, what happens if some COG have different internal colormap). The way mosaic works it's really hard to access the `raw` data. 

We are working on a new mosaicjson specification to make this easier. I just created https://github.com/developmentseed/mosaicjson-spec/issues/15 to keeps this in mind

**Comment by vincentsarago** [comment]
> the documentation example runs with another version of the app, so that was a bit confusing initially.

Yeah I'm sorry about that, because mosaic needs to be written somewhere I had no choice than using the modified version of titiler (for security reason). I'll see if I can create another demo using a local titiler deployment!

**Comment by dzanaga** [comment]
> yes this is expected because it's a mosaic, it's hard to know if we should use the internal mosaic (e.g what if some COG don't have colormap, what happens if some COG have different internal colormap). The way mosaic works it's really hard to access the `raw` data.

I see, thanks for the explanation. Being able to add a colormap to the MosaicJSON (or automatically read it from the first tif...) sounds like a nice solution.

Anyways, thanks for sharing your amazing work!
