### ISSUE TITLE
Use `rio_cogeo.cog_info` in cog `/info` endpoint

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#193]
rio_cogeo.cog_info offers way more `info` than the default `info()` method from COGReader. 

We just need to subclass the TilerFactory in `cog.py`

**Comment by kylebarron** [comment]
> rio_cogeo.cog_info offers way more `info` than the default `info()` method from COGReader.

Why? Why couldn't they both return the same info? Or maybe the default `rio_tiler.Info` class contains everything except the validation keys.

**Comment by vincentsarago** [comment]
> Why couldn't they both return the same info

Well by design we choose rio-tiler info (when we started rio-tiler) to be quite simple and it didn't change much over the time. 

rio-cogeo info is brand new and tried to match what aiocogeo and tifffile libraries were returning.

with rio-tiler 2.0 being release, I don't think changing the rio-tiler readers right now would be a good idea! 

we have two choice: 
- keep info as it is right now (so it's the same for all the readers
- use rio-cogeo info for the /cog endpoint if we think the user wants more info for their COG

**Comment by vincentsarago** [comment]
rio-tiler COGReader `info` method returns more info now, still not at the level of rio-cogeo info but I think it's fine for now. 

If a user really wants it, it's pretty simple to customize the TileFactory
