### ISSUE TITLE
Docs page with explanation of relevant GDAL environment variables

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/titiler#240]
#### Problem description

There are many GDAL environment variables, and it's hard to know the implications of each of them just from reading the GDAL documentation.

I think I can start a PR on this. Possible start:

- `CPL_VSIL_CURL_ALLOWED_EXTENSIONS`: A list of extensions that GDAL is allowed to open. For example if set to `.tif`, then GDAL wouldn't open any other files. For example, it wouldn't open JPEG2000 files with a `.jp2` extension, but also wouldn't open Geotiffs exposed through an API endpoint that don't have a `.tif` suffix.
- `GDAL_HTTP_MULTIPLEX`. Only applies with HTTP2, which not all servers support, but when set to `YES` and uses HTTP2, can download multiple ranges in parallel. 
- `GDAL_INGESTED_BYTES_AT_OPEN`: Gives the number of bytes GDAL should read for COG headers. 
	- Explain how to see header of average dataset with `aiocogeo info`. Vincent says you can't get it from GDAL.
- `GDAL_DISABLE_READDIR_ON_OPEN`: Depends on the source data.
- `GDAL_HTTP_MERGE_CONSECUTIVE_RANGES`: Set to `YES` to merge ranges when possible. 

Unknown env vars:

- CPL_VSIL_CURL_NON_CACHED
- VSI_CACHE

Ref: https://trac.osgeo.org/gdal/wiki/ConfigOptions

**Comment by vincentsarago** [comment]
`CPL_VSIL_CURL_NON_CACHED` this one is to make sure nothing is cached for a path or a pattern. I use it here https://github.com/developmentseed/tilebench/blob/master/tilebench/viz.py#L75-L78

> Starting with GDAL 2.3, the CPL_VSIL_CURL_NON_CACHED configuration option can be set to values like /vsicurl/http://example.com/foo.tif:/vsicurl/http://example.com/some_directory, so that at file handle closing, all cached content related to the mentioned file(s) is no longer cached. This can help when dealing with resources that can be modified during execution of GDAL related code. Alternatively, VSICurlClearCache() can be used.


`CPL_VSIL_CURL_CHUNK_SIZE` can also be a nice one

> Partial downloads (requires the HTTP server to support random reading) are done with a 16 KB granularity by default. Starting with GDAL 2.3, the chunk size can be configured with the CPL_VSIL_CURL_CHUNK_SIZE configuration option, with a value in bytes. If the driver detects sequential reading it will progressively increase the chunk size up to 2 MB to improve download performance. Starting with GDAL 2.3, the GDAL_INGESTED_BYTES_AT_OPEN configuration option can be set to impose the number of bytes read in one GET call at file opening (can help performance to read Cloud optimized geotiff with a large header).
