### ISSUE TITLE
COG endpoint documentation does not mention colormap_name parameter

### ISSUE THREAD

**Issue by zacharyDez** [developmentseed/titiler#272]
#### Problem description

The current documentation found at *docs/endpoints/cog.md* does not mention the colormap_name parameter. Once I found the Swagger UI docs, I figured out that there was another parameter to use rio colormaps. 😅 

#### Expected Output

Fixed documentation. 

#### Proposed solution

I am willing to open a pull request to update the documentation. I preferred engaging in conversation with the dev team before making any changes. 

Is simply changing the related markdown files in the docs folder sufficient to fix the documentation here: https://developmentseed.org/titiler/? 

Are there any current efforts to update the documentation? Is this issue related to any others?

Let me know how I can help 😄

**Comment by vincentsarago** [comment]
@zacharyDez, yes sorry I forgot to update the docs.

> I am willing to open a pull request to update the documentation

🙏 please go ahead

basically you need to update all files in https://github.com/developmentseed/titiler/blob/master/docs/endpoints which mention the `color_map` parameter 

Thanks

**Comment by vincentsarago** [comment]
maybe some notebooks are not up to date also. but api.cogeo.xyz hasn't been updated yet 😬

**Comment by zacharyDez** [comment]
@vincentsarago made changes locally. Trying to push local branch and open a PR. I seem to not have the permissions to push to do so.  Is there some workflow not mentioned in contributing.md? Or can you simply give me the rights?

**Comment by vincentsarago** [comment]
@zacharyDez you need to:
1. `fork` TiTiler to your own account
2. create a branch on your fork
3. push changes
4. go on GitHub and open a PR from your fork to TiTiler 

ref: https://github.com/firstcontributions/first-contributions

**Comment by vincentsarago** [comment]
I'm keeping this open, until I fix the rest of the documentation

**Comment by zacharyDez** [comment]
Hi @vincentsarago, 

Working on implementing a custom TMS in MTM8. Starting the discussion here because it relates to the docs, sorry if you prefer having another issue opened. 

The user guide documentation on [tile matrix sets](https://developmentseed.org/titiler/concepts/tile_matrix_sets/) points to a [broken link](https://developmentseed.org/titiler/concepts/tile_matrix_sets/concepts/customization/#custom-tms) on custom Tile Matrix Sets. 

I also found this documentation on [Custom TMS](https://developmentseed.org/titiler/concepts/customization/#custom-tms). 

I tried the following steps to implement the custom TMS.

I've created a custom TMS in *tms.py*:
```python
# CUSTOM TMS for EPSG:2951
# info from https://epsg.io/2950
MTM8 = morecantile.TileMatrixSet.custom(
    (-5133537.37, 7003006.85, 494955.36, 9654280.93),
    CRS.from_epsg(2950),
    identifier="MTM8",
    matrix_scale=[1, 1],
)
```

and added in the registration in *dependencies.py*:

```python
tms = tms.register([custom_tms.EPSG3413, custom_tms.EPSG6933, custom_tms.MTM8])
```

I can now hit the endpoint `tileMatrixSets/MTM8` successfully. 

However, I haven't been able to access a valid cog endpoint in the new TMS: `http://{{host}}:{{port}}/cog/tiles/{z}/{x}/{y}.?url={{img_url}}`.

I was wondering if the following steps are given in the customization documentation still necessary:

```python
# 3. Create ENUM with available TMS
TileMatrixSetNames = Enum(  # type: ignore
    "TileMatrixSetNames", [(a, a) for a in sorted(tms.list())]
)

# 4. Create Custom TMS dependency
def TMSParams(
    TileMatrixSetId: TileMatrixSetNames = Query(
        TileMatrixSetNames.WebMercatorQuad,  # type: ignore
        description="TileMatrixSet Name (default: 'WebMercatorQuad')",
    )
) -> TileMatrixSet:
    """TileMatrixSet Dependency."""
    return tms.get(TileMatrixSetId.name)

# 5. Create Tiler
COGTilerWithCustomTMS = TilerFactory(
    reader=COGReader,
    tms_dependency=TMSParams,
)

```


Is there an on-going effort to update the docs on implementing a custom TMS? I would be happy to contribute once I get I get it working on my end.

**Comment by vincentsarago** [comment]
@zacharyDez appreciate the feedback 🙏 
Docs are certainly missing some features/update 

Feel free to start a discussion over https://github.com/developmentseed/titiler/discussions

> However, I haven't been able to access a valid cog endpoint in the new TMS: http://{{host}}:{{port}}/cog/tiles/{z}/{x}/{y}.?url={{img_url}}.

I'm not sure to understand, but if you follow the previous steps you should be able to get the tiles using your new TMS with 
```
http://{{host}}:{{port}}/cog/tiles/MTM8/{z}/{x}/{y}?url={{img_url}}
```

`MTM8` should also be present as a valid choice for TileMatrixSet in the api documentation `http://{{host}}:{{port}}/docs`

**Comment by vincentsarago** [comment]
FYI, I've pushed a quite big documentation update (mostly cleaning up and renaming files)

**Comment by vincentsarago** [comment]
notebook and doc should be up to date now!
