### ISSUE TITLE
color_map=coolwarm behavior changed

### ISSUE THREAD

**Issue by susman** [developmentseed/titiler#302]
#### Problem description
Hello,
First allow me to thank you guys for this amazing project. We at CarbonSpaceTech are using it (and rio-tiler) extensively and are very happy with the results titiler produces.

I can't pin point exactly since which version the regression happened. In our prod env we're using an older version of docker image from docker hub sha256:cb9798ba758bd2975c5bdd7b1cc40d55fc623faf6cf98e1496033f225343f038 (now non-existent) and it works as expected, color_map=coolwarm does actually produce matplotlib coolwarm palette. Latest version, from both, docker hub and AWS ECR (public.ecr.aws/developmentseed/titiler:latest), generates shades of gray instead of coolwarm.

![titiler-bug-gray](https://user-images.githubusercontent.com/4905409/115967992-d0cede00-a535-11eb-86ea-a0826c45f7a3.png)

#### Expected Output
Expected color palette:
![titler-bug-coolwarm](https://user-images.githubusercontent.com/4905409/115968018-e2b08100-a535-11eb-8c0c-0ffd2183cdeb.png)

#### Environment Information
The "good" version : ~3 months old docker image from docker hub sha256:cb9798ba758bd2975c5bdd7b1cc40d55fc623faf6cf98e1496033f225343f038
The "bad" version: public.ecr.aws/developmentseed/titiler:latest

**Comment by vincentsarago** [comment]
@susman this is not a bug, it was mentioned in https://github.com/developmentseed/titiler/blob/master/CHANGES.md#020-2021-03-09

TiTiler is in heavy development (recent 0.3.0 version changed a lot of things again). Make sure to used tags when you use docker images.

**Comment by susman** [comment]
My apologies, totally missed this.

**Comment by vincentsarago** [comment]
no worries @susman. As I mentioned, TiTiler is in active dev, we try to avoid breaking changes but as the project is relatively young those has to happen sometime 🙁
