### ISSUE TITLE
Use starlette-cramjam compression middleware

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#312]
link: https://github.com/milesgranger/pyrus-cramjam

right now we have to install brotli dependency and use default middleware which is not customizable (ref https://github.com/developmentseed/titiler/discussions/268)

I think we could create a simple middleware which support zlib and brotli using pyrus-cramjam and also add a `path` filter as we've done in https://github.com/developmentseed/titiler/pull/297

**Comment by kylebarron** [comment]
> I think we could create a simple middleware which support zlib and brotli using pyrus-cramjam and also add a `path` filter as we've done in #297

Are these two different issues? One to change the compression implementation from the defaults to a third party package, and a separate one to add a `path` filter to the middleware? Seems like you could subclass the existing middleware to add a `path` filter without changing the compression implementation?

**Comment by vincentsarago** [comment]
@kylebarron it's kinda 2 issues in one

1. we need a custom middleware to filter based on path or media type
2. we need one solution that could support brotli and zlib 


Creating a brand new middleware based on pyrus-cramjam will let us do what ever we think is good ;-)

**Comment by vincentsarago** [comment]
I started something over https://github.com/developmentseed/starlette-cramjam but for now I'm blocked at making streamed response working!

**Comment by vincentsarago** [comment]
💥 https://pypi.org/project/starlette-cramjam/0.1.0a0/ thanks a lot to @milesgranger for his great help 🙏
