### ISSUE TITLE
Lambda S3 bucket permissions are too permissive

### ISSUE THREAD

**Issue by philvarner** [developmentseed/titiler#329]
#### Problem description

This describes a code issue and an example issue related to granting s3 bucket permissions to the lambda.

The examples for giving bucket permissions look like:

```
TITILER_STACK_BUCKETS='["my-bucket*", "*"]'
```

The code that creates the permissions looks like:

```
if settings.buckets:
            perms.append(
                iam.PolicyStatement(
                    actions=["s3:GetObject", "s3:HeadObject"],
                    resources=[f"arn:aws:s3:::{bucket}*" for bucket in settings.buckets],
                )
            )
```

One issue is that the example should be `my-bucket` rather than `my-bucket*`, since that ends up with an s3 permission on `arn:aws:s3:::my-bucket**` and ``arn:aws:s3:::**` (double wildcard), which is no different than a single *. Most users likely want to only grant access to the exactly-named bucket, not all buckets prefixed with that value, so I think it is a misleading example.

However, even with a TITILER_STACK_BUCKETS that only has `my-bucket`, I think the resource URN generated for the permissions should have a `/` between the bucket and *, e.g., `arn:aws:s3:::{bucket}/*`, because `arn:aws:s3:::{bucket}*` gives permissions to *any* bucket that is prefixed with the TITILER_STACK_BUCKETS value, not just all the objects in the one named buckets. 

I could imagine a scenario where a user had buckets `foo` and `foo-private`, and putting just `foo` in TITILER_STACK_BUCKETS is inadvertently granting access to `foo-private`. 

#### Expected Output

A CFN template that only has exactly the access to the buckets specified.

#### Environment Information

Os, Python version, ...

**Comment by vincentsarago** [comment]
@philvarner thanks for the report. Do you have a solution for this? 

is 
```python
if settings.buckets:
    perms.append(
        iam.PolicyStatement(
            actions=["s3:GetObject", "s3:HeadObject"],
            resources=[f"arn:aws:s3:::{bucket}/*" for bucket in settings.buckets],
        )
    )
```
what should be the proper CFN?

**Comment by philvarner** [comment]
Yes, if the intention is to give access to all the objects in the bucket.

**Comment by vincentsarago** [comment]
> Yes, if the intention is to give access to all the objects in the bucket.

maybe we can add a `key` settings (with default to `*`):

```python
if settings.buckets:
    perms.append(
        iam.PolicyStatement(
            actions=["s3:GetObject", "s3:HeadObject"],
            resources=[f"arn:aws:s3:::{bucket}/{settings.key}" for bucket in settings.buckets],
        )
    )
```
