### ISSUE TITLE
deployment on nginx - https  protocol

### ISSUE THREAD

**Issue by jaysnm** [developmentseed/titiler#344]
Hi
My appreciations to the team maintaining this project. It adds lots of capabilities not supported by rio-viz. Have found it incredible at what it does!

#### Problem description  
I have been able to experiment COG tiler capabilities on local setup with nginx used as a proxy server. Moving to production, I introduced certificates routing all traffic to https. A `/cog/metadata` request returns expected data from my local setup (http) but fails on production setup (https) with 
```
CURL error: Failed to connect to domain.xx port 443: Connection refused
'/vsicurl/https://domain.xxx/stac/catalog-item/my-item.tif' not recognized as a supported file format.
```
Same errors are emitted when calling tilejson endpoint to render tiles on map.

The `/cog/viewer` endpoint generates html content with tilejson_endpoint and metadata_endpoint defined on http protocol despite that I'm running the service on https.

```
const tilejson_endpoint = "http://jdomain.xx/cog/tilejson.json"
const metadata_endpoint = "http://domain.xx/cog/metadata"
```

#### Environment Information
I'm running developmentseed/titiler docker image with the port exposed being used by nginx to proxy_pass the service.

**Comment by vincentsarago** [comment]
@jaysnm I don't think this is a bug or has anything to do with TiTiler? 

I think the error you are seeing is related to GDAL libcurl not being able to use ssl. 

I'm going to move this to the `discussion` board and at the same time it could help if you provide more info about how you installed titiler. my first hint is you could try to set https://github.com/developmentseed/titiler/blob/master/Dockerfile#L3
