### ISSUE TITLE
s3:HeadObject is not a valid AWS IAM policy Action

### ISSUE THREAD

**Issue by philvarner** [developmentseed/titiler#353]
#### Problem description

Deploying titiler with CDK gives a warning that s3:HeadObject is not an S3 Action. This is because it is not per the documentation here: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html 

The fix is to simply remove this Action from the policy definition(s), as s3:GetObject also allows the head operation.

#### Expected Output

No warning about policy actions.

#### Environment Information

n/a

**Comment by vincentsarago** [comment]
@philvarner I don't see any mention of HeadObject in titiler code https://github.com/developmentseed/titiler/blob/2168c9284b39a46c4d1a095542c77addc690a738/deployment/aws/cdk/app.py#L168-L177

we updated this 3 month ago https://github.com/developmentseed/titiler/pull/330/files#diff-ce02ebe86b6992fd0e07623a204ba559d8654e02518b6d6da2b98a6000e7ab25L172

**Comment by philvarner** [comment]
Sorry! I was looking at an old version of the code.
