### ISSUE TITLE
[STAC] resolves relative asset path

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#36]
like in https://github.com/Terradue/stac-resources/blob/master/kompsat-3a/item.json

**Comment by fabricebrito** [comment]
Hello @vincentsarago, great project, well done! :-)

This feature would ease our setup as the STAC catalogues we use move from a location to another and this is why we use relative hrefs also for the asset paths. For instance pystac resolves the the full href with e.g. 

```python
item.assets['nbr'].get_absolute_href()
``` 

So definitely a +1 here

**Comment by vincentsarago** [comment]
excellent, I'm going to close this issue here because this is in fact a rio-tiler issue. I'll open one there
