### ISSUE TITLE
titiler.core requires fastapi < 0.66

### ISSUE THREAD

**Issue by mkaminsky** [developmentseed/titiler#366]
#### Problem description

I've been playing around with titiler, and it seems really nice—thanks!  I would like to experiment using titiler.core to add /cog endpoints to my own FastAPI-based project.  Currently, titiler is restricted to versions of FastAPI < 0.66 (the latest version is 0.68.1).  Is there something about the more recent releases that is incompatible, or is it safe to remove that restriction?

#### Output

```bash
$ poetry add titiler.core
Using version ^0.3.8 for titiler.core

Updating dependencies
Resolving dependencies... (3.8s)

  SolverProblemError

  Because titiler.core (0.3.8) depends on fastapi (>=0.65,<0.66)
   and no versions of titiler.core match >0.3.8,<0.4.0, titiler.core (>=0.3.8,<0.4.0) requires fastapi (>=0.65,<0.66).
  So, because project depends on both fastapi (^0.68.0) and titiler.core (^0.3.8), version solving failed.
```
#### Expected Output

Adding package succeeds.

#### Environment Information

Linux, Python 3.9, poetry

**Comment by vincentsarago** [comment]
> Is there something about the more recent releases that is incompatible, or is it safe to remove that restriction?

Yes, see:
- https://github.com/stac-utils/stac-fastapi/issues/242
- https://github.com/stac-utils/stac-fastapi/pull/246
- https://github.com/developmentseed/geojson-pydantic/issues/42

So while openapi/fastapi won't support Tuple with defined length we won't be able to update fastapi>0.67 

FYI pinning FastAPI is recommended by fastapi docs https://fastapi.tiangolo.com/deployment/versions/#pin-your-fastapi-version

**Comment by vincentsarago** [comment]
Note: I think it will be ok to update the version to `>=0.65,<0.68` to enable stac-fastapi and titiler

**Comment by mkaminsky** [comment]
Thanks for the quick reply.  Makes sense--I do recall seeing that OpenAPI Tuple length issue at some point.

Pinning to an earlier version of FastAPI seems to work smoothly.
