### ISSUE TITLE
"not recognized as a supported file format" errors

### ISSUE THREAD

**Issue by Plantain** [developmentseed/titiler#409]
Using the Lambda deployment, ~25% of requests to a COG mosaic tile fail with "not recognized as a supported file format." errors. The problematic files seem to change randomly (all are valid COG's), and the error seems transient as later that same tile and file will work just fine (seemingly on a new Lambda instance).

I think it likely points back to https://github.com/rasterio/rasterio/issues/1686

I tried changing GDAL_DISABLE_READDIR_ON_OPEN to FALSE, but it doesn't seem to help - that appears to have worked around the race condition(?) for other users by making it slower.

#### Environment Information

Lambda, git HEAD.

**Comment by vincentsarago** [comment]
👋 @Plantain, 25% seems really high. I've seen some errors but not at this level. Are you using the lambda configuration as set in https://github.com/developmentseed/titiler/blob/master/deployment/aws/cdk/config.py#L77-L82 https://github.com/developmentseed/titiler/blob/master/deployment/aws/cdk/config.py#L20-L30 

FYI https://titiler.xyz is deployed with those default (but with 3008 memory). If you are using public files, you can try it and see if you get the same results.

**Comment by Plantain** [comment]
I'm not able to reproduce it on that endpoint - I am using the default Lambda configuration, but I am doing a COG mosaic with almost unaltered code from https://devseed.com/titiler/examples/code/mosaic_from_urls/ , with 5 COG's - I guess because it's 5x as many COG's the chances of a failure are exponentially higher.

**Comment by vincentsarago** [comment]
can you try setting `MOSAIC_CONCURENCY=1`(or `RIO_TILER_MAX_THREAD=1` in the environment https://github.com/developmentseed/titiler/blob/master/src/titiler/mosaic/titiler/mosaic/factory.py#L219

Mosaic requires much more time/memory/CPU so you might want to bump the default configuration to higher memory (higher memory in lambda also means higher CPU and bandwidth).

**Comment by kylebarron** [comment]
I always thought I hit the "not recognized as a supported file format" errors when I was using multithreading in Lambda. Especially when you only have 5 COGs, I think that makes it much more likely that multiple requests will be hitting the same physical file on the backend. My impression was that the error came from multiple threads on the same machine reading from the same file concurrently. I believe forcing max thread to 1 fixed my issues, but not sure.

**Comment by Plantain** [comment]
Unfortunately, RIO_TILER_MAX_THREAD=1 did not seem to help

**Comment by vincentsarago** [comment]
🤦 it's `RIO_TILER_MAX_THREADS` https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/constants.py#L12

**Comment by vincentsarago** [comment]
closing this for now, feel free to re-open. IMO, this is either a configuration issue or a GDAL/rasterio/rio-tiler one. Dealing with concurrent reading and cache is not trivial.

**Comment by rsignell-usgs** [comment]
I'm getting this error on our lambda deployment.

The `titiler.xyz` endpoint works correctly:
https://titiler.xyz/cog/bounds?url=s3://cmgp-sfm-public-read-bucket/Hx_Ian/ortho/20221003_FL_4D_RuPaReX2_RGBAvg_fullres_UTM17_cog.tif
returning:
``` 
{"bounds":[-82.49502732167822,26.5747555527131,-82.20355769677433,27.179190003126966]}
```
but our `titiler.usgs.gov` endpoint fails:
https://titiler.usgs.gov/cog/bounds?url=s3://cmgp-sfm-public-read-bucket/Hx_Ian/ortho/20221003_FL_4D_RuPaReX2_RGBAvg_fullres_UTM17_cog.tif
returning:
``` 
{"detail":"'/vsis3/cmgp-sfm-public-read-bucket/Hx_Ian/ortho/20221003_FL_4D_RuPaReX2_RGBAvg_fullres_UTM17_cog.tif' not recognized as a supported file format."}
```
Do we have some configuration parameter set incorrectly?

**Comment by rsignell-usgs** [comment]
Aha!  Okay, thanks!
