### ISSUE TITLE
Add exception handling

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/titiler#41]
Currently the app either returns a 200 on successful request or server error (500) on unsuccessful request.  I think there is a lot of value in explicitly raising exceptions for error cases.  Most important in my opinion is `FileNotFound` and `TileNotFound` errors which both should return a `404` status code indicating that the particular file/tile was not found.  These status codes, if raised, may be used by the client to infer that there is no imagery available for the particular request and to fall back to another data source or provider.

I think the best way to do this is [global exception handlers](https://fastapi.tiangolo.com/tutorial/handling-errors/#install-custom-exception-handlers) which return a particular status code whenever a specific exception is raised.  This is inline with having [standardized exceptions](https://github.com/developmentseed/titiler/blob/master/titiler/errors.py) within the app (which is already implemented, although they aren't currently used anywhere).

**Comment by vincentsarago** [comment]
please!

**Comment by geospatial-jeff** [comment]
Ok, I can add in a follow up PR to #40

**Comment by vincentsarago** [comment]
let's start of list of common exception we want to catch: 

- rio_tiler.errors.TileOutsideBounds (404)
- any GDAL error (e.g filenot found) (404)
- Not able to render (should be a GDAL error)  (500 ?)
- `BadRequestError, TileNotFoundError` for mosaics  (500 ?)
- rio_tiler.errors.InvalidBandName (404 ?)
