### ISSUE TITLE
Remove intermediary api router

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/titiler#42]
The fastapi router defined in `titiler.api.api` doesn't really add much.  I can see a use case for using an intermediary router if that router used a particular custom defined route class etc. but that isn't the case here.  It would be better to attach the routes directly to the fastapi app defined in `titiler.main`, remove `titiler.api.api`, and maybe rename `titiler.main` -> `titiler.app` to be more standard with fastapi conventions.

**Comment by vincentsarago** [comment]
👍
