### ISSUE TITLE
Docker images are not published on Docker hub

### ISSUE THREAD

**Issue by AndreaGiardini** [developmentseed/titiler#433]
Hello everyone

Since version 0.4.0a2 docker images are not published anymore on the Docker hub: https://hub.docker.com/r/developmentseed/titiler/tags
Maybe a pipeline broke?

**Comment by vincentsarago** [comment]
https://github.com/developmentseed/titiler/discussions/408

use GitHub registry please https://github.com/developmentseed/titiler#docker
