### ISSUE TITLE
COG colormap issues

### ISSUE THREAD

**Issue by iferencik** [developmentseed/titiler#454]
#### Problem description

I am trying to render a tile with a custom colormap and I have run into some issues. I have a float32 COG [[info enpoint here]](https://undp.livedata.link/hrea/fullinfo?url=https://undpngddlsgeohubdev01.blob.core.windows.net/testforgeohub/HREA_Algeria_2012_v1%2FAlgeria_rade9lnmu_2012.tif?c3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAxVDE5JTNBNDYlM0EyMVomc3I9YiZzcD1yJnNpZz10TjhCQzVVajB5S2tDQ3VTMjBrYVZwWW5TJTJCTWJJUWhRV0gwZVRaUkU5aW8lM0Q=)

Rendering the tile using [colormap_name](https://undp.livedata.link/hrea/tiles/10/508/404.png?scale=1&TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Fundpngddlsgeohubdev01.blob.core.windows.net%2Ftestforgeohub%2FHREA_Algeria_2012_v1%2FAlgeria_rade9lnmu_2012.tif%3Fc3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAxVDE5JTNBMjklM0EyMlomc3I9YiZzcD1yJnNpZz1TRjNrdGdMeXJhQ0ExaHlrcmklMkZvUnRka1FscWcwTGNDak9lcXpKQWxPNTQlM0Q%3D&bidx=1&unscale=false&resampling=nearest&rescale=0.9%2C8.3&return_mask=true&colormap_name=reds) yields, which is fine.
![404](https://user-images.githubusercontent.com/92793531/161140027-ddf78518-7bf1-4787-944f-7456d7cf7aca.png)

However, using a custom  interval based  [colormap](https://undp.livedata.link/hrea/tiles/10/508/404.png?scale=1&TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Fundpngddlsgeohubdev01.blob.core.windows.net%2Ftestforgeohub%2FHREA_Algeria_2012_v1%2FAlgeria_rade9lnmu_2012.tif%3Fc3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAxVDE5JTNBMjklM0EyMlomc3I9YiZzcD1yJnNpZz1TRjNrdGdMeXJhQ0ExaHlrcmklMkZvUnRka1FscWcwTGNDak9lcXpKQWxPNTQlM0Q%3D&bidx=1&unscale=false&resampling=nearest&rescale=0.9%2C8.3&return_mask=true&colormap=[[[0.9,2.38],[255,245,240,255]],[[2.3899999999999997,3.87],[252,187,161,255]],[[3.88,5.35],[251,106,74,255]],[[5.359999999999999,6.84],[203,24,29,255]],[[6.85,8.32],[103,0,13,255]]]) yields

![404](https://user-images.githubusercontent.com/92793531/161139938-cd338046-b555-44b1-b813-e700587924b6.png)

this is the  JSON colormap:
```
[
    [[0.9,2.38],[255,245,240,255]],
    [[2.3899999999999997,3.87],[252,187,161,255]],
    [[3.88,5.35],[251,106,74,255]],
    [[5.359999999999999,6.84],[203,24,29,255]],
    [[6.85,8.32],[103,0,13,255]]
]
```

I was not expecting any transparent holes in the colormap rendered image and so far I am not able to understand why is this happening

Thanks in advance

**Comment by vincentsarago** [comment]
@iferencik your interval bounds do not fully describe the data. the `max` of one interval should be the `min` of the next interval (https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/colormap.py#L188) 


```python
cmap = [
    [
        [0.9,2.38],[255,245,240,255]
    ],
    [
        [2.38,3.87],[252,187,161,255]
    ],
    [
        [3.87,5.35],[251,106,74,255]
    ],
    [
        [5.35,6.84],[203,24,29,255]
    ],
    [
        [6.84,8.32],[103,0,13,255]
    ]
]
``` 


![10-508-404](https://user-images.githubusercontent.com/10407788/161212049-1535a37f-7a64-4581-80a8-08b945f43127.jpg)

**Comment by iferencik** [comment]
@vincentsarago thanks.

Long story short. I originally had the same colormap like yours but it was not working. The reason why is different though, and namely the rescale parameter: rescale=layermin,layermax

this is working as expected with your colormap:

https://undp.livedata.link/hrea/tiles/10/508/404.png?scale=1&TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Fundpngddlsgeohubdev01.blob.core.windows.net%2Ftestforgeohub%2FHREA_Algeria_2012_v1%2FAlgeria_rade9lnmu_2012.tif%3Fc3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAxVDE5JTNBMjklM0EyMlomc3I9YiZzcD1yJnNpZz1TRjNrdGdMeXJhQ0ExaHlrcmklMkZvUnRka1FscWcwTGNDak9lcXpKQWxPNTQlM0Q%3D&bidx=1&unscale=false&resampling=nearest&return_mask=true&colormap=[[[0.9,2.38],[255,245,240,255]],[[2.38,3.87],[252,187,161,255]],[[3.87,5.35],[251,106,74,255]],[[5.35,6.84],[203,24,29,255]],[[6.84,8.32],[103,0,13,255]]]
![404](https://user-images.githubusercontent.com/92793531/161223618-5b396845-e566-4b02-917c-81962e229392.png)




when I add  the rescale 


https://undp.livedata.link/hrea/tiles/10/508/404.png?scale=1&TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Fundpngddlsgeohubdev01.blob.core.windows.net%2Ftestforgeohub%2FHREA_Algeria_2012_v1%2FAlgeria_rade9lnmu_2012.tif%3Fc3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAxVDE5JTNBMjklM0EyMlomc3I9YiZzcD1yJnNpZz1TRjNrdGdMeXJhQ0ExaHlrcmklMkZvUnRka1FscWcwTGNDak9lcXpKQWxPNTQlM0Q%3D&bidx=1&unscale=false&resampling=nearest&rescale=0.9%2C8.32&return_mask=true&colormap=[[[0.9,2.38],[255,245,240,255]],[[2.38,3.87],[252,187,161,255]],[[3.87,5.35],[251,106,74,255]],[[5.35,6.84],[203,24,29,255]],[[6.84,8.32],[103,0,13,255]]]
![404](https://user-images.githubusercontent.com/92793531/161223571-9bb2c370-a3e4-43ee-a9e4-728096535b60.png)


I am using the rescale to limit the range of the datasets and allow users to change the display of the layers on this way.
I'd realy like to understand how the rescale is being used here. COudl you point me to the source code that does this?


Thank you again

**Comment by vincentsarago** [comment]
The `rescale` parameter will rescale value from min,max to `0,255` https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/utils.py#L358-L378 and then we will apply the colormap. 

in 
https://github.com/developmentseed/titiler/blob/master/src/titiler/core/titiler/core/factory.py#L501-L511

we first do `postprocess` (e.g rescaling) then then we create the image (applying colormap)

**Comment by iferencik** [comment]
That is exactly how I understood.

I do have another interesting case. this time I am using an int type dataset ([info here](https://undp.livedata.link/hrea/fullinfo?url=https://undpngddlsgeohubdev01.blob.core.windows.net/testforgeohub/USA_POPDEN_2020_COG_1km_rec2.tif?c3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAyVDA5JTNBMTIlM0EzNVomc3I9YiZzcD1yJnNpZz1ZVG9nOUFjVU1zaGVyU3hpWm9QeFBRQXViTEVaZ3JNZ1JGJTJGc2lCVlVQYzAlM0Q=))

This call will take some time because I am scanning the whole file to get the  unique values.

The dataset is in range (1000-3000) with  three unique values (1000, 2000, 3000)

this is the url that will generate the tile

https://undp.livedata.link/hrea/tiles/8/53/98.png?scale=1&TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Fundpngddlsgeohubdev01.blob.core.windows.net%2Ftestforgeohub%2FUSA_POPDEN_2020_COG_1km_rec2.tif%3Fc3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAyVDA5JTNBMTIlM0EzNVomc3I9YiZzcD1yJnNpZz1ZVG9nOUFjVU1zaGVyU3hpWm9QeFBRQXViTEVaZ3JNZ1JGJTJGc2lCVlVQYzAlM0Q%3D&bidx=1&unscale=false&resampling=nearest&rescale=1000%2C3000&return_mask=true&colormap={%220%22%3A[63%2C74%2C138%2C255]%2C%22127%22%3A[31%2C157%2C138%2C255]%2C%22255%22%3A[254%2C232%2C37%2C255]}

![98](https://user-images.githubusercontent.com/92793531/161235441-8c9b7ffc-e42e-4c6f-b084-5a30c0fb9022.png)


and it looks just as I expect it to

When I zoom out however the middle color (green) dissapears (pixels become transparent).

https://undp.livedata.link/hrea/tiles/6/11/23.png?scale=1&TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Fundpngddlsgeohubdev01.blob.core.windows.net%2Ftestforgeohub%2FUSA_POPDEN_2020_COG_1km_rec2.tif%3Fc3Y9MjAyMS0wNC0xMCZzZT0yMDIyLTA0LTAyVDA5JTNBMTIlM0EzNVomc3I9YiZzcD1yJnNpZz1ZVG9nOUFjVU1zaGVyU3hpWm9QeFBRQXViTEVaZ3JNZ1JGJTJGc2lCVlVQYzAlM0Q%3D&bidx=1&unscale=false&resampling=nearest&rescale=1000%2C3000&return_mask=true&colormap={%220%22%3A[63%2C74%2C138%2C255]%2C%22127%22%3A[31%2C157%2C138%2C255]%2C%22255%22%3A[254%2C232%2C37%2C255]}


![23](https://user-images.githubusercontent.com/92793531/161235901-92f4926a-cb49-4ac1-86ce-be46723f199a.png)


Could this be because the server is using the overviews and this zoom level and the value 2000 that corresponds to the green color does not exist in the overviews?


This does not happen with a copy of this layer whose range is in interval 1-3 with unique values 1,2,3

**Comment by vincentsarago** [comment]
> Could this be because the server is using the overviews and this zoom level and the value 2000 that corresponds to the green color does not exist in the overviews?

do you know which resampling you used to create the overview? I don't think you used `nearest` which should present
See: [USA_POPDEN_2020_COG_1km_rec2_nearest.tif.zip](https://github.com/developmentseed/titiler/files/8397540/USA_POPDEN_2020_COG_1km_rec2_nearest.tif.zip)
 
```
$ rio cogeo create USA_POPDEN_2020_COG_1km_rec2.tif USA_POPDEN_2020_COG_1km_rec2_nearest.tif --blocksize 512 --overview-blocksize 512 --overview-level 5 --forward-band-tags
```

Note: if you have only 3 values, it would be better you use byte datatype + internal colormap ;-) 
Note2: in titiler you can use the `/statistics` endpoint with `categorical=True` options to return the unique values of your dataset.
