### ISSUE TITLE
Install on Digital Ocean Ubuntu 20.04 - No module named "morecantile" 

### ISSUE THREAD

**Issue by gagecarto** [developmentseed/titiler#474]
Installing from source on a Digital Ocean Ubuntu 20.04 with Python 3.8.10 instance fails. Do I need to install other python dependencies before tying titiler?

`git clone https://github.com/developmentseed/titiler.git`
`cd titiler`
`pip install -e src/titiler/core -e src/titiler/mosaic -e src/titiler/application`

![image](https://user-images.githubusercontent.com/5776766/168331198-70a8a8e1-bed8-46e2-8b9e-7e875c1d1513.png)

**Comment by vincentsarago** [comment]
can you make sure you have setuptools up to date 
```
pip install setuptools>=0.40 -U
```
