### ISSUE TITLE
add more documentation about rendering options

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#507]
colormaps: https://cogeotiff.github.io/rio-tiler/colormap/
rescaling
color_formula
...

**Comment by vincentsarago** [comment]
some nice examples: https://docs.charter.uat.esaportal.eu/webPortal/geobrowser/titiler/

**Comment by dchirst** [comment]
I'll start looking at this one next (since I can't assign myself to a task).

**Comment by vincentsarago** [comment]
done in #620 🙏
