### ISSUE TITLE
Return asset ids as response header

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/titiler#51]
Users often want to see metadata information on the client about the imagery shown. This is especially true for mosaics, but also desirable for single-scene COG viewing.

I propose adding a response header like `X-ASSETS` that returns a comma-separated or JSON-encoded list of asset ids that were used to create the response tile. For many sources, the asset id includes enough information to extract a date range and other helpful metadata.

**Comment by vincentsarago** [comment]
> I propose adding a response header like X-ASSETS that returns a comma-separated or JSON-encoded list of asset ids that were used to create the response tile. For many sources, the asset id includes enough information to extract a date range and other helpful metadata.

with the new cogeo-mosaic `BaseBackend` method this might be a bit tricky. Especially if we want `list of asset ids that were used to create the response tile`. An *easy*  solution would be for `tile` to return the whole list of assets passed to the `tiler` but this won't mean that they were used.

ref: https://github.com/developmentseed/cogeo-mosaic/blob/c989249ecda0ab090e5fff86e6aba2ba8c882f3f/cogeo_mosaic/backends/base.py#L59-L72

```python
    def tile(
        self, x: int, y: int, z: int, **kwargs: Any,
    ) -> Tuple[numpy.ndarray, numpy.ndarray]:
        """Get Tile from multiple observation."""

        assets = self.assets_for_tile(x, y, z)
        if not assets:
            raise NoAssetFoundError(f"No assets found for tile {z}-{x}-{y}")

        def _reader(asset: str, x: int, y: int, z: int, **kwargs: Any):
            with self.reader(asset) as src_dst:
                return src_dst.tile(x, y, z, **kwargs)

        return mosaic_reader(assets, _reader, x, y, z, **kwargs)
```
so in ☝️ do `return mosaic_reader(assets, _reader, x, y, z, **kwargs), assets`

we could also try to change `mosaic_reader` and https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/mosaic/reader.py#L19-L52 but not sure it will work.

**Comment by kylebarron** [comment]
> An _easy_ solution would be for `tile` to return the whole list of assets passed to the `tiler` but this won't mean that they were used

That's actually what I expected, but maybe it's worth considering trying to return only what was used
