### ISSUE TITLE
Pencil/edit icon in documention links to old paths

### ISSUE THREAD

**Issue by rushgeo** [developmentseed/titiler#524]
#### Problem description

Each page of the [documentation](https://developmentseed.org/titiler/) has a pencil icon ("Edit this page") that links to the documentation source. These links point to the old URLs, before documentation was moved into a `src` subdiretory.

#### Expected Output
Clicking the pencil icon on https://developmentseed.org/titiler/intro/ should link to 
https://github.com/developmentseed/titiler/blob/master/docs/src/intro.md 
but it links to 
https://github.com/developmentseed/titiler/blob/master/docs/intro.md
which is a 404.

**Comment by vincentsarago** [comment]
thanks for the report 🙏 @rushgeo 

closed in https://github.com/developmentseed/titiler/commit/2fa5d26efea9eb003a8d6ec276e5cdd285845c75
