### ISSUE TITLE
OGC API - Tiles 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#546]
The OGC just published https://ogcapi.ogc.org/tiles/

To be clear, TiTiler DO NOT AIM to follow the specification to the letter (because the specification is not built around dynamic tiling but more on static tiling) but we can try to follow some part.

- `/tileMatrixSets`: List available TMS (already implemented)
- `/tileMatrixSets/{TileMatrixSetId}`: TMS metadata (already implemented)
- `/conformance` 

Note: The Tile spec is based on the TMS 2.0 specification so we will have to update morecantile first

full spec https://docs.ogc.org/is/20-057/20-057.html

**Comment by dchirst** [comment]
@vincentsarago Once Morecantile 4.0 is fully released,I can start working on this!

**Comment by vincentsarago** [comment]
🙏

**Comment by vincentsarago** [comment]
Quick update, I don't think we will be able comply with the OGC Tile 2.0 specification. 

We will be able to update the `tilematrixset` (like https://github.com/developmentseed/tipg/blob/main/tipg/factory.py#L1275-L1364) but for the other endpoints it will be pretty hard. 

## DataSet Collection (`{datasetAPI}/collections/{collectionId}/tiles`) 

We don't have collections in titiler! Some could think that `/cog` or `/mosaic` could be collectionId but this will makes things more complex. 

Also the specification is pretty strict about the query parameter for the endpoints, and `url=dataset url` won't be accepted. 

## TileSet

example: https://github.com/developmentseed/tipg/blob/main/tipg/factory.py#L1366-L1555

We might still want to add `tileset` but I'm not sure it will be worth it especially knowing that it's pretty much impossible to titiler to be OGC compliant. 


I personally, as the project maintainer, don't see any obligation to comply with OGC specification because TiTiler has existed for quite some time already and I never had official requests to make it so.
