### ISSUE TITLE
bad tiles

### ISSUE THREAD

**Issue by fabry24** [developmentseed/titiler#566]
#### Problem description
I've noticed that after upgrading to 0.8.0 and above, there is a problem with tiles that don't fall into the current zoom level.
This problem has been occurring since the access to TMS was changed from version 0.8.0. I tried to changed titiler/core/factory.py and titiler/core/dependency.py and mosaic/titiler/mosaic/factory.py from version 0.10.2 to old access for tms from 0.8.0 and it works correctly.
I'm using /cog/tiles/{z}/{x}/{y} endpoint and WebMercatorQuad tms and rescale @1x

#### Expected Output
This is expected output
![image](https://user-images.githubusercontent.com/78112061/208911794-2307d4a1-5dc6-4fed-b92d-aacc84c55b72.png)
![image](https://user-images.githubusercontent.com/78112061/208919296-87c7847a-d3e6-4a1a-b7ff-7d4ea1960e92.png)

This is our problem with bad tiles
![image](https://user-images.githubusercontent.com/78112061/208919071-535a66dd-4a32-4381-8699-65e944b5675c.png)
![image](https://user-images.githubusercontent.com/78112061/208919253-daf6a872-3482-43f5-875b-00b73ee0f141.png)

Am I doing something wrong in the current version?
Thank for help.

**Comment by vincentsarago** [comment]
@fabry24 I believe I've fixed this yesterday 🙈  https://github.com/cogeotiff/rio-tiler/blob/main/CHANGES.md#415-2022-12-20

**Comment by vincentsarago** [comment]
@fabry24 can you confirm ☝️ fixed it and close the issue 🙏

**Comment by fabry24** [comment]
I confirm that your uprgade works. Thank you for your help.
