### ISSUE TITLE
rio-tiler version in latest build

### ISSUE THREAD

**Issue by fabry24** [developmentseed/titiler#567]
Hello,
this problem is related to #566.
You do some changes in rio-tiler and my problem with bad tiles is gone. but it is neccessary to update rio-tiler to version 4.1.5 manually.
Locally I use docker-composer but I also use latest build from github. In your latest build is version rio-tiler 4.1.4 and problem from #566 is still active.

It is possible to use latest version of rio-tiler in latest build or I have to wait for next latest build?

**Comment by vincentsarago** [comment]
@fabry24 I've re-published all the docker image and they should have the latest version of rio-tiler now 🙏

**Comment by fabry24** [comment]
When I run
`docker run --name titiler -p 8000:8000 --env PORT=8000 --env WORKERS_PER_CORE=1 --rm -it ghcr.io/developmentseed/titiler:latest`, then rio-tiler has version 4.1.5

Thank you for your quick response and help
