### ISSUE TITLE
In stac endpoint docs, asset_bidx is "Asset1|1;2;3", but should be 'Asset1|1,2,3"

### ISSUE THREAD

**Issue by philvarner** [developmentseed/titiler#592]
In stac endpoint docs, the asset_bidx param has:

```
asset_bidx (array[str]): Per asset band math expression (e.g Asset1|1;2;3).
```

`1;2;3` is invalid (titiler returns an error about not being able to parse it as an int) as this requires comma-separated values, e.g., `1,2,3`

**Comment by vincentsarago** [comment]
fixed in https://github.com/developmentseed/titiler/commit/65bba2f186d2c70a44e3eb10d839a33f6e6387b7 thanks for the report 🙏
