### ISSUE TITLE
Docs: Add step for upgrading pip

### ISSUE THREAD

**Issue by mradamcox** [developmentseed/titiler#601]
#### Problem description

I am installing a local build for development as described here, https://developmentseed.org/titiler/#installation, and ran into an issue with the fact that there is no `setup.py` in the app, only `pyproject.toml`. Turns out, this is just a problem with pip <21.3 (I had 20 by default in my virtual environment). Upgrading allowed me to make an editable install without any trouble.

Adding

```
python -m pip install --upgrade pip
```

as a first step in those commands may be helpful for others in the future.

#### Environment Information
Ubuntu 20.04, Python 3.8.10 (using `venv` for virtual environment)

**Comment by vincentsarago** [comment]
`pip install -U pip` is the first line in https://developmentseed.org/titiler/#installation 

```
$ pip install -U pip
$ pip install uvicorn
$ pip install titiler.{package}
``` 

🤷‍♂️

**Comment by vincentsarago** [comment]
I added a bit more doc with https://github.com/developmentseed/titiler/commit/9dccc4d9c53dccc592298429f9454ded6113c2e0

sorry if you lost time on this issue.

**Comment by mradamcox** [comment]
Oh, well no I was just looking at the second section and now I feel silly  :facepalm: . Sorry for missing that! No worries.

**Comment by vincentsarago** [comment]
no worry, I didn't see that you were talking about the `local build` section. I added it there too. 

it took me some times but now I'm doing `pip install -U pip` every two weeks or so 😅
