### ISSUE TITLE
Errors building Tiler with cache

### ISSUE THREAD

**Issue by guillemc23** [developmentseed/titiler#605]
Hey! 
I'm trying to add cache to my Titiler instance, but I bumped into this line while following the docs.

https://github.com/developmentseed/titiler/blob/27b4972f21b245a4ca6bfcffae369a30e1171d0b/docs/src/examples/code/tiler_with_cache.md?plain=1#L169

In this line, it's trying to import `MetadataParams` (which is not used anywhere on the rest of the code, so I guess it should be removes) and `TMSParams`. Both of this names result in errors when importing as in:
```
ImportError: cannot import name 'MetadataParams' from 'titiler.core.dependencies' (/opt/bitnami/python/lib/python3.11/site-packages/titiler/core/dependencies.py)
```
```
ImportError: cannot import name 'TMSParams' from 'titiler.core.dependencies' (/opt/bitnami/python/lib/python3.11/site-packages/titiler/core/dependencies.py)
```

I am unable to find any reference to any of those dependencies in the [official documentation](https://devseed.com/titiler/api/titiler/core/dependencies/). Were they moved/refactored/deprecated? How should I proceed to configuring Titiler with cache?

I'm running Titiler on a docker image from `ghcr.io/developmentseed/titiler:latest`.

Thank you!

**Comment by vincentsarago** [comment]
this example is old and should be updated, sorry about that

**Comment by vincentsarago** [comment]
fixed https://github.com/developmentseed/titiler/blob/c8c19b4809f1ca77c1db845a4e7c0332690189c2/docs/src/examples/code/tiler_with_cache.md

**Comment by guillemc23** [comment]
Hello again Vincent, the cache is working, but when an item is cached, it's returning a Starlette response object as in `<starlette.responses.Response object at 0x7fc64bfd3850>` that can't be understood by the browser nor Postman. `media_type` looks correct. 

 I think I'm missing something. Could you point me towards the right direction?

When loading a resource for the first time, works like a charm 😄

**Comment by guillemc23** [comment]
@vincentsarago I wasn't able to make it work, but I foung another Python library that's newer and, according to them, faster than aiocache. It works with memory or redis and solves this issue mentioned in the docs:
> Because aiocache.cached doesn't support non-async method we have to create a custom cached class

So it reduces the amount of code and it's much easier to set up :D

If you're interested I can PR with the solution I found with this new library.

https://pypi.org/project/cashews/

**Comment by vincentsarago** [comment]
> If you're interested I can PR with the solution I found with this new library.

🙏 yes that would be lovely
