### ISSUE TITLE
New version of FastAPI breaks Titiler

### ISSUE THREAD

**Issue by dchirst** [developmentseed/titiler#609]
#### Problem description

A new version of FastAPI (v0.95.0) came out yesterday, and I've found that it breaks Titiler and stops it from running. 
When I run `uvicorn titiler.application.main:app` I get:

`AssertionError: Cannot use `Query` for path param 'TileMatrixSetId'`.

Installing FastAPI v0.94.1 fixes the issue

#### Expected Output

A running titiler server

#### Environment Information

MacOS Ventura, Conda/Mamba, python 3.11

Steps to recreate error:
```
mamba create -n titilererror python=3.11 -y
mamba activate titilererrror
pip install titiler.application fastapi==0.95.0
uvicorn titiler.application.main:app
```

**Comment by vincentsarago** [comment]
interesting I'm not able to reproduce this on python 3.9

**Comment by vincentsarago** [comment]
confirmed https://github.com/developmentseed/titiler/actions/runs/4460968838/jobs/7834461429

**Comment by vincentsarago** [comment]
this is because we are creating multiple routes for one endpoint with option Path Parameter (as Query). It used to work until now 😭 

https://github.com/tiangolo/fastapi/discussions/9278
