### ISSUE TITLE
Tiling with resampling=lanczos adds border to COG edges

### ISSUE THREAD

**Issue by showcaseearth** [developmentseed/titiler#662]
#### Problem description

Using `tiles/` endpoints with `resampling=lanczos` adds a border to the edges of the rendered pixels at low to mid zoom levels. It is most obvious on straight edges (pictured below), but the easiest public example I have is from OAM. Adjusting other parameters did not seem to help, nor did I see any other common resampling methods produce a similar effect at any zoom level. 

If this is upstream of titiler, then please let me know and I'll move accordingly! 

Example using `cog/tiles/15/18272/12136@1x.png?TileMatrixSetId=WebMercatorQuad&url=https%3A%2F%2Foin-hotosm.s3.us-east-1.amazonaws.com%2F649d03872fb3a800012c9e6d%2F0%2F649d03872fb3a800012c9e6e.tif&resampling=lanczos` , with another nonpublic rectangular example below to better illustrate. 

lanczos vs nearest
<img width="552" alt="image" src="https://github.com/developmentseed/titiler/assets/77654787/fcd4cf7f-4204-4332-a75e-4dc35d8476b3">

#### Expected Output
No border added, like other resampling methods. 

#### Environment Information

AWS deployment of titiler 0.11.6

**Comment by vincentsarago** [comment]
@showcaseearth thanks for opening the issue.

If there is something, it will be either on rio-tiler/rasterio side. Would you be able to re-open this issue in https://github.com/cogeotiff/rio-tiler/discussions (maybe first as a discussion and then we can iterate to see if there is a bug or if it comes from the data) 🙏

**Comment by showcaseearth** [comment]
Thanks @vincentsarago , opened here: https://github.com/cogeotiff/rio-tiler/discussions/622
