### ISSUE TITLE
jsonschema >= 4.18.1  causes extensions test failure

### ISSUE THREAD

**Issue by philvarner** [developmentseed/titiler#667]
#### Problem description

With jsonschema >= 4.18.1 , running

```
python -m pytest src/titiler/extensions --cov=titiler.extensions --cov-report=xml --cov-append --cov-report=term-missing
```

results in 

```
FAILED src/titiler/extensions/tests/test_stac.py::test_stacExtension - jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/assets'
```

<= 4.18.0 works fine. 

#### Expected Output

successful test

#### Environment Information

macOS, python 3.10.4

**Comment by vincentsarago** [comment]
I've added a fix in https://github.com/developmentseed/titiler/pull/664/files#diff-062a3ec46b13209016b5e8cc7512ba060a75619d00fbc06507d7674530dee605R41 just in case
