### ISSUE TITLE
Band names in expression are now lower case only

### ISSUE THREAD

**Issue by glaroc** [developmentseed/titiler#668]
?expression=sqrt(B1)

used to work but in current titiler version expression needs to be

?expression=sqrt(b1)

This is not really a problem, but the examples in the doc use uppercase B.

**Comment by glaroc** [comment]
For example, in every QueryParams section here:
https://github.com/developmentseed/titiler/blob/main/docs/src/endpoints/cog.md

**Comment by vincentsarago** [comment]
fixed in https://github.com/developmentseed/titiler/commit/9dc9d6b978053a32e8455e5e7c55388edb91070b 🙏
