### ISSUE TITLE
/preview and /crop with max_size returns different result

### ISSUE THREAD

**Issue by fabry24** [developmentseed/titiler#682]
#### Problem description

I am using two titiler endpoint /crop and /preview with max_size parameter=1024
When I use /preview, I get result wih 1024 HEIGHT and computed width.
When I use /crop with whole raster extent, I get result with 1024 WIDTH and computed height

I can not use width and height parameters. I need max_size parameter.

#### Expected Output
In both cases I need to the same result with height=1024 and with computed width.

Is this bug or not?

Thank you for any help.

**Comment by vincentsarago** [comment]
@fabry24 I'm not sure to understand.

can you provide the urls you're using?

If there is a bug it will be on rio-tiler side. you can easily confirm with 

```python

from rio_tiler.io import Reader

with Reader(your_file) as src:
    preview = src.preview(max_size=1024, width=None, height=None)
    crop = src.part(src.bounds, max_size=1024, width=None, height=None)

    print(preview.data.shape)
    print(crop.data.shape)
```

**Comment by fabry24** [comment]
oooooh, I did bad analyse of my problem. results from titiler enpoints are OK, width and height computed from max_size are good. this issue can be closed.

thanks.
