### ISSUE TITLE
Load first three image bands as RGB

### ISSUE THREAD

**Issue by tayden** [developmentseed/titiler#685]
#### Problem description

Currently, the TiTiler viewer loads the first COG band for the red channel, the second band for the green channel, and the final (e.g. 4th band in a 4 band image) as the blue channel. I would like to see this changed to just load the first three bands as the RGB channels, instead of the unusual behaviour for loading the blue channel that currently exists.

![image](https://github.com/developmentseed/titiler/assets/6541671/7ded6e31-932c-47f3-8837-402d1cefa924)

For imagery that, e.g. include an NIR channel, the channel order is typically R-G-B-NIR (or B-G-R-NIR, sometimes). In my opinion, the bands I would want to load are nearly never the first, second, and fourth bands for visualization purposes, and loading the first, second, and third bands is a much better default since it would usually load a true-color image.

#### Expected Output
By default:

![image](https://github.com/developmentseed/titiler/assets/6541671/e7c5e2b7-09d6-4764-9754-8f4d117bfedd)

I'm happy to submit a PR for this, if it helps get it done.

**Comment by vincentsarago** [comment]
@tayden PR is more than welcomed 🙏

**Comment by vincentsarago** [comment]
done in #688
