### ISSUE TITLE
replace `_` by `-` in query parameter names?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#692]
Right now we have a mix of both `-` and `_` in query parameters names. I think it will be better to be coherent and use only one notation `-` (or `_`) 

ref https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

looking at https://www.terminusapp.com/blog/dash-or-underscore-in-urls/ it seems some people prefer using `_` 🤷 

### `_` parameters:

- `colormap_name` 
- `asset_indexes`
- `asset_as_band`
- `asset_expression`
- `max_size`
- `resampling_method`
- `return_mask`
- `histogram_bins`
- `histogram_range`
- `color_formula` 
- `tile_format` 
- `tile_scale`
- `pixel_selection`  (Mosaic)
- `with_eo` (STAC extension)
- `with_raster ` (STAC extension)
- `with_proj` (STAC extension)
- `asset_href` (STAC extension)
- `asset_media_type`  (STAC extension)
- `asset_roles` (STAC extension)
- `asset_name` (STAC extension)
- `collection_url` (STAC extension)

### `-` parameters

- `coord-crs`
- `dst-crs` 
- `geom-densify-pts` (STAC extension)
- `geom-precision`  (STAC extension)

Let's hear your opinions!

**Comment by vincentsarago** [comment]
While I love making breaking changes, I think we should keep all `_` parameters and just changed the ones with `-`

**Comment by emmalu** [comment]
To me, `_` is the [geospatial] way...
