### ISSUE TITLE
titiler deployment without CDN - alternative deployment scenarios

### ISSUE THREAD

**Issue by fabricebrito** [developmentseed/titiler#72]
I'm wondering if there are alternative deployment scenarios without CDN for titiler. 

We've deployed titiler on a large single machine and the performance are of course not a good as your endpoint.

What would be the alternative deployment scenario for acceptable performance on a private cloud? Our use-cases include using titiler for restricted access data in a private cloud deployment.

**Comment by vincentsarago** [comment]
@fabricebrito I never deployed titiler on a single machine. The endpoint you tested is deployed on AWS Lambda, but we also have tested on AWS ECS (with a minimum of 2 tasks) and it worked great too. 

Maybe the performance could be better if you use only 1 worker per core! (the default is set to 5 in the docker-compose.yml but I should change this).

**Comment by fabricebrito** [comment]
We've also set 1 worker per core. 
How was your setup on AWS ECS? Maybe we could reproduce that configuration on a private cloud

**Comment by fabricebrito** [comment]
We've deployed  a load balancer in front of two servers and that was enough to get the same range of performances.
I hope this helps future users in their deployments of this great tool

**Comment by smajida** [comment]
@fabricebrito 
@vincentsarago 
I would like to load a COG images which are covering a large area over MapBox map hosted on a private server. Could you please let me know how did you mange to do that?

**Comment by vincentsarago** [comment]
@smajida I'm not sure to understand your question. Have you looked at the docs https://developmentseed.org/titiler/
also your question doesn't seems to be related with Fabrice origin Issue, please open a new one if needed

**Comment by smajida** [comment]
@vincentsarago 
Yes I have, but I got a bit confused. 
This issue was the closest issue which I found to my question. 
Okay. I will open a new issue.
