### ISSUE TITLE
Can not get wms layers from GetCapabilities

### ISSUE THREAD

**Issue by whisper-bye** [developmentseed/titiler#756]
http://localhost:8000/cog/wms?request=GetCapabilities
python 3.11

{
  "detail": "Missing WMS 'LAYERS' parameter."
}

**Comment by zacharyDez** [comment]
Hi Len,

I'm guessing you already extended your application with the WMS extension. You need to provide the path to your COG under the layers parameters in the request. You'll also need to specify `service=WMS`. Feel free to provide more information about your data in the discussions!
