### ISSUE TITLE
0.17.1 is not released to pypi

### ISSUE THREAD

**Issue by JinIgarashi** [developmentseed/titiler#795]
#### Problem description

I saw the version was bumped to 0.17.1 in GitHub, but I realized this version is not yet released to pypi when I tried to update titiler version in our app. I could not install titiler 0.17.1

https://github.com/developmentseed/titiler/blob/c18d09e53f198e70e97e27e13e2b5a59a64ae427/pyproject.toml#L33-L38

In pypi, 0.17.0 is the latest as of 14 March 2024
https://pypi.org/project/titiler/#history

#### Expected Output

0.17.1 should be also released to pypi as well

#### Environment Information

Os, Python version, ...

**Comment by vincentsarago** [comment]
🤯 thanks for the report. It's really weird. I'll try to fix this ASAP

**Comment by vincentsarago** [comment]
all good now, not sure what happened to GitHub yesterday 🤷
