### ISSUE TITLE
Deleting Github Tags!

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#88]
We are now really close to the next TiTiler release. 🎉 

We have refactored the code to create a proper python module with helper classes like the new `titiler.endpoint.factory.TilerFactory` which will help users to integrate COG/STAC/MosaicJSON tilers (FastAPI router) directly to thier applications

```python
from titiler.endpoints.factory import TilerFactory
from fastapi import FastAPI

app = FastAPI()

cog = TilerFactory()

print([r.path for r in cog.router.routes])
> [
    '/openapi.json',
    '/docs',
    '/docs/oauth2-redirect',
    '/redoc',
    '/bounds',
    '/info',
    '/metadata',
    '/tiles/{TileMatrixSetId}/{z}/{x}/{y}@{scale}x.{format}',
    '/tiles/{TileMatrixSetId}/{z}/{x}/{y}@{scale}x',
    '/tiles/{TileMatrixSetId}/{z}/{x}/{y}.{format}',
    '/tiles/{TileMatrixSetId}/{z}/{x}/{y}',
    '/tiles/{z}/{x}/{y}@{scale}x.{format}',
    '/tiles/{z}/{x}/{y}@{scale}x',
    '/tiles/{z}/{x}/{y}.{format}',
    '/tiles/{z}/{x}/{y}',
    '/{TileMatrixSetId}/tilejson.json',
    '/tilejson.json',
    '/{TileMatrixSetId}/WMTSCapabilities.xml',
    '/WMTSCapabilities.xml',
    '/point/{lon},{lat}',
    '/preview.{format}',
    '/preview',
]
app.include_router(cog.router, tags=["Cloud Optimized GeoTIFF"])

```

Because of the PyPi release I think it makes sense to start the release at version 0.0.1 and get rid of old tags

**Comment by kylebarron** [comment]
Why not start at `0.1.0`? That seems more standard than starting at `0.0.1`?

**Comment by vincentsarago** [comment]
thanks @kylebarron makes sense 

ref: https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase
