### ISSUE TITLE
route resolution fails when titiler is mounted as a subapp

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/titiler#95]
`request.url_for` fails to find the correct route when titiler is mounted as a sub application (https://github.com/developmentseed/titiler/blob/nonTMSReader/titiler/endpoints/factory.py#L1013):

```python
from fastapi import FastAPI
from titiler.endpoints.stac import STACTiler

app = FastAPI()

titiler_app = FastAPI()
titiler_app.include_router(STACTiler().router)

app.mount("/titiler", titiler_app)
```
This is because `request.url_for` uses the router of the request's current scope which in this case is `app` and not `titiler_app`.  Because sub applications are independent of the parent app, the titiler routes are not actually registered on `app`, so starlette can't find the route and raises `starlette.routing.NoMatchFound`.

A solution that works is replacing calls to `request.url_for` with `self.router.url_path_for` which has the same signature (its called under the hood by `request.url_for`) but only searches the specific router, ensuring that route resolution will always work no matter how the app is mounted.

**Comment by vincentsarago** [comment]
oh that's nice, maybe we don't need the prefix then?

**Comment by geospatial-jeff** [comment]
Yeah I think the prefix could be removed with this

**Comment by vincentsarago** [comment]
I tried the `self.router.url_path_for` it nice but sadly it returns an absolute path. You can prefix this with the `request.base_url` but then it's missing prefix (if you mount the router with one, like we do for COG or STAC). 

👇 this is working (basically searching for prefix in the request's `path`) but I'm not sure it's the best approach.
```python
base_url = str(request.base_url)
prefix = request["path"].replace(f"/{tms.identifier}", "").replace("/tilejson.json", "")
if prefix:
    base_url = base_url + prefix.lstrip("/")

relative_tiles_url = self.router.url_path_for("tile", **kwargs)
tiles_url = relative_tiles_url.make_absolute_url(base_url=base_url)


```
