### ISSUE TITLE
There is a memory leak problem in wmsExtension

### ISSUE THREAD

**Issue by RS-Y** [developmentseed/titiler#954]
When I use the titiller application, I add the wmsExtension of the cog.Then I found that the memory used by uvicorn kept increasing and would not be released：
![image](https://github.com/user-attachments/assets/59339233-3109-4d37-a53e-b8a05ab21e0b)
![image](https://github.com/user-attachments/assets/103123d9-038a-48f7-860e-92e120523cea)

**Comment by vincentsarago** [comment]
Dear @RS-Y

We know there is something going on but we've been unable to really put a finger about where exactly it is.

But if you have reproducible example to share or more info please you're more than welcome 

I'm going to close this issue but feel free to continue the thread over https://github.com/cogeotiff/rio-tiler/issues/713
