### ISSUE TITLE
add support for the STAC Render extension

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#974]
https://github.com/developmentseed/titiler/blob/725f857c735790e6c7783c4319f61804669b1980/src/titiler/core/titiler/core/factory.py#L1143C7-L1143C28

as done in https://github.com/stac-utils/titiler-pgstac/blob/a66493516cc8271674724daf73802e5254675b2f/titiler/pgstac/factory.py#L456-L633 or https://github.com/developmentseed/titiler-stacapi/blob/721439432d1d84d6eb76202b857475fdee7d8722/titiler/stacapi/factory.py#L573-L702

**Comment by ormsbydaniel** [comment]
I believe this would be very useful for the UK EODH project /cc @j08lue

**Comment by j08lue** [comment]
Can you please describe briefly what the goal is, @vincentsarago?

1. Will I be able to point TiTiler at an item and it will pick up the render parameters automatically?
2. Will it work for searches / mosaics?
3. Will it work for render information defined only on collection level?

**Comment by vincentsarago** [comment]
> Will I be able to point TiTiler at an item and it will pick up the render parameters automatically?

No, the idea is to have a new `/renders` endpoint that gives you properly built tilejson URL

> Will it work for searches / mosaics?

renders is already partially supported by titiler-pgstac

> Will it work for render information defined only on collection level?

for titiler-pgstac it works for collection level but for titiler the render should be at item level 


FYI there is a PR https://github.com/developmentseed/titiler/pull/1034 that was started during SATSummit stac sprint and others contributors reaching out to finish this PR. I won't be available to work on this right now but we might put this back on the priority list at some point
